### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by canDry** [bigeyex/python-adminui#11]
The quick start example on the README.md has this syntax error:  
  
>> TextField('Title', required=True),  
s.b. TextField('Title', required_message="..."), 
  
Also, the error messages are in Chinese.  

Looks promising though.  I like the simplicity of the design.

**Comment by bigeyex** [comment]
updated the example to fix this issue. Thanks or pointing it out. 
Error messages in my system are not Chinese though. Please attach screenshots if possible. This project is written in English, so the Chinese messages are mostly possible coming from ant-design, the underlying library.
