### ISSUE TITLE
example webpage stuck

### ISSUE THREAD

**Issue by edwardsun** [bigeyex/python-adminui#2]
After the example service is started, the webpage 127.0.0.1:5000 is stuck and hangs forever.
![image](https://user-images.githubusercontent.com/359830/72403176-36a5b500-378c-11ea-9e0d-3dcd478ddbc4.png)
![image](https://user-images.githubusercontent.com/359830/72403213-48875800-378c-11ea-88b3-f4a0b236674d.png)

**Comment by edwardsun** [comment]
Is there any missing dependency? I've only done "pip install adminui" and "pip install pyjwt". Windows 10.

**Comment by bigeyex** [comment]
would you please re-test it in the new 0.2.2 and see if the issue is still there?

**Comment by bigeyex** [comment]
Would you please paste the error log in the console?

**Comment by edwardsun** [comment]
actually there was no error message. The info message is posted in the original post.

**Comment by edwardsun** [comment]
Confirming the cmd log as follows:

![image](https://user-images.githubusercontent.com/359830/72582607-3e955e80-391e-11ea-91f9-939148507083.png)

**Comment by bigeyex** [comment]
Seemingly it's about the browser cache. Would you please hard refresh = refresh when inspector open or right-click the refresh button to see if it works?

**Comment by edwardsun** [comment]
No it did not work out...
![image](https://user-images.githubusercontent.com/359830/72934987-86ddd200-3d9f-11ea-8555-d578377a4827.png)

**Comment by bigeyex** [comment]
or you may try pip install adminui==0.3.1 to force install a newer version.
Seemingly some files are outdated.

**Comment by edwardsun** [comment]
![image](https://user-images.githubusercontent.com/359830/73222455-41097b00-419e-11ea-97ec-96206f3cea5f.png)
No luck. I noticed that there are 404 errors in the highlighted area. Maybe this can shed some light?

**Comment by bigeyex** [comment]
Would you please try it in a [Python virtual environment](https://docs.python.org/3/tutorial/venv.html)?

I tried it in venv and it runs without problems. I wonder if your pip and python commands are in different Python instance or something, So some files are always missing.

**Comment by edwardsun** [comment]
Closing the ticket as the issue only stays on one Win 10 computer. Another Win10 machine and Linux machines are fine.
