### ISSUE TITLE
Chart columns

### ISSUE THREAD

**Issue by harry3689** [bigeyex/python-adminui#23]
Hi,

In example_dash.py, there are two data given for displaying charts, _visit_data_  and _offline_chart_data_ . In offline_chart_data there are three data points x, y1 and y2 and while using that data to display LineChart and BarChart it does not get rendered, but the default visit_data gets displayed. Is this a known issue?

Best regards,
Harry

**Comment by bigeyex** [comment]
Yes, that example data is not used. It's prepared for future features.
