### ISSUE TITLE
Support new Antd components

### ISSUE THREAD

**Issue by jwag59** [bigeyex/python-adminui#25]
It would be really great if there were a few more Antd component elements available. The current programming model for adminui is really convenient and more components would enable it to be used for slightly more complex applications.
In particular, could you consider supporting:
- Radio buttons/Radio group 
- More table options including:
    - sort option for columns
    - column filtering
    - column search
 - Modals
 - Pie chart
 
Of course Antd supports many other components to these but even with these few additional components it would be possible to cover many other areas of use.
I appreciate your consideration of these.

**Comment by jwag59** [comment]
Thankyou for quickly supporting Radio and Sort/filter options.

**Comment by bigeyex** [comment]
fulfilled in 1.4.0
