### ISSUE TITLE
Chinese text on login page

### ISSUE THREAD

**Issue by jwag59** [bigeyex/python-adminui#27]
Is there a simple way to remove the Chinese text from the login page? For example, can we set a locale somewhere to change this text to English. 
I have actually rebuilt adminui after modifying the text for the login page to remove the Chinese text but this action would be required after every update to adminui.
The text is at the top and the bottom of the page.
See the following screenshot.
![login_screen_chinese_text](https://user-images.githubusercontent.com/22910903/166658895-cbfef030-0ae1-4e6d-aa1b-10f60a32dd19.png)

**Comment by bigeyex** [comment]
Lol, I removed the Chinese text on the login page for now. Apparently, there's a lot to do with customizing these appearances.
