### ISSUE TITLE
Login page shows a big Ant Design text instead of the app.title

### ISSUE THREAD

**Issue by jwag59** [bigeyex/python-adminui#30]
Would it be possible to get the app.title. on the login page instead of the large Ant Design text?
Users should be presented with the name of the application they are logging into not the component library used.
See screenshot
![login_page_antdesign](https://user-images.githubusercontent.com/22910903/167376343-0dce4a5c-d843-41eb-8d36-e4c3bd6aab23.png)

**Comment by bigeyex** [comment]
fixed in 1.2.3
