### ISSUE TITLE
Login page still has Chinese characters in the Copyright statement at the bottom.

### ISSUE THREAD

**Issue by jwag59** [bigeyex/python-adminui#31]
Is it possible to remove the copyright or at least the Chinese characters in the copyright test at the bottom of the login page?
Note: Once a user logs in then then the text is displayed in English.
![login_page_copyright_chinese](https://user-images.githubusercontent.com/22910903/167377109-684ca32b-6ce4-4cfe-a1c6-fa1955d4ccf7.png)

**Comment by bigeyex** [comment]
fixed in 1.2.3
