### ISSUE TITLE
NavigateTo produces a 404 when the page has multiple page levels in the URL 

### ISSUE THREAD

**Issue by jwag59** [bigeyex/python-adminui#35]
When a destination URL is not at the root of the application, then NavigateTo produces a 404 page not found error.
For example I have a URL named /cluster/ngrps
I have a menuitem that specifies /cluster/ngrps which displays normally. However if I try to NavigateTo content at /clusters/ngrps/2 then I get a 404.
In fact /clusters/ngrps/2 should make 2 as a parameter to the URL /clusters/ngrps and I display a different set of content in this case.

When I was using URLs of /nrps and /ngrps/2 then everything worked just fine. It seems there is a problem when using multiple levels in the URL. 
Can you please review and let me know about this. And just let me know if there is any debugging information I can get to help with this.
Perhaps I can make a small mockup to send you.

**Comment by jwag59** [comment]
The code snippet which shows what I mean is:

```
@app.page('/cluster/ngrps', 'Nodegroups')
def ngrps_view_page(param):
    print("param='%s'" % param)
    if len(param) < 1:
        return nglist_layout()
    else:
        return ngview_layout(param)
```

However when I issue a NavigateTo('/cluster/ngrps/2') this function (ngrps_view_page) is NEVER called!! and a 404 error is displayed instead.

**Comment by jwag59** [comment]
Here is a complete working example that shows a multi-level URL does not work with a parameter and NavigateTo.

```
#!/usr/bin/env python3.8

from adminui import *

app = AdminApp()

@app.page('/', 'Dashboard')
def dashboard_page():
    return [
        Header("This is our Dashboard home page", 1)
    ]

def on_node_param1():
    return NavigateTo("/nodes/2")

@app.page('/nodes', 'Nodes list')
def nodes_L1_page(param):
    if len(param) < 1:
        return [
            Header("This is our /nodes page", 1),
            Button("Go to page with Parameter (works)", style='primary', on_click=on_node_param1)
        ]
    else:
        return [
            Header("This is our /nodes page with a passed parameter: %s" % param, 1)
        ]


def on_node_param2():
    return NavigateTo("/cluster/nodes/2")

@app.page('/cluster/nodes', 'Lower Nodes list')
def nodes_L2_page(param):
    if len(param) < 1:
        return [
            Header("This is our /cluster/nodes page", 1),
            Button("Go to page with Parameter (doesn't work)", style='danger', on_click=on_node_param2)
        ]
    else:
        return [
            Header("This is our /cluster nodes page with a passed parameter: %s (never gets displayed)" % param, 1)
        ]

app.set_menu(
    [
        MenuItem('Home', '/', icon="dashboard"),
        MenuItem('Cluster', '/cluster', icon="cluster",
                children=[
                    MenuItem('Nodes', '/cluster/nodes', icon="database"),
                ]
        ),
        MenuItem('Nodes', '/nodes', icon="info-circle")
    ]
)


if __name__ == '__main__':
    app.run(host='0.0.0.0', port=8000)
```

**Comment by jwag59** [comment]
Here is a better example that includes subpages with and without parameters. The URL's with multiple depths always fail.

```
#!/usr/bin/env python3.8

from adminui import *

app = AdminApp()

@app.page('/', 'Dashboard')
def dashboard_page():
    return [
        Header("This is our Dashboard home page", 1)
    ]

def on_node_param1():
    return NavigateTo("/nodes/2")

@app.page('/nodes/add', 'Nodes add sub-page')
def nodes_add_subpage1():
    return [
        Header("This is our /nodes/add page", 1)
    ]

def on_node2_add1():
    return NavigateTo("/nodes/add")

@app.page('/nodes', 'Nodes list')
def nodes_L1_page(param):
    if len(param) < 1:
        return [
            Header("This is our /nodes page", 1),
            Row([
                Column([Button("Go to page with Parameter (works)", style='primary', on_click=on_node_param1)])
            ]),
            Row([
                Column([Button("Go to sub-page without a Parameter (works)", style='primary', on_click=on_node2_add1)])
            ])
        ]
    else:
        return [
            Header("This is our /nodes page with a passed parameter: %s" % param, 1)
        ]

@app.page('/cluster/nodes/add', 'Nodes add sub-page2')
def nodes_add_subpage2():
    return [
        Header("This is our /nodes/add page", 1)
    ]

def on_node_add2():
    return NavigateTo("/cluster/nodes/add")

def on_node_param2():
    return NavigateTo("/cluster/nodes/2")

@app.page('/cluster/nodes', 'Lower Nodes list')
def nodes_L2_page(param):
    if len(param) < 1:
        return [
            Header("This is our /cluster/nodes page", 1),
            Row([
                Column([Button("Go to page with Parameter (doesn't work)", style='danger', on_click=on_node_param2)])
            ]),
            Row([
                Column([Button("Go to sub-sub-page without a Parameter (doesn't works)", style='danger', on_click=on_node_add2)])
            ])
        ]
    else:
        return [
            Header("This is our /cluster nodes page with a passed parameter: %s (never gets displayed)" % param, 1)
        ]

app.set_menu(
    [
        MenuItem('Home', '/', icon="dashboard"),
        MenuItem('Cluster', '/cluster', icon="cluster",
                children=[
                    MenuItem('Nodes', '/cluster/nodes', icon="database"),
                ]
        ),
        MenuItem('Nodes', '/nodes', icon="info-circle")
    ]
)


if __name__ == '__main__':
    app.run(host='0.0.0.0', port=8000)

```

**Comment by bigeyex** [comment]
Thanks for your detailed examples. Currently, Admin UI doesn't support multi-level URL yet. 

This is because, if the URL is like '/cluster/1', AdminUI knows '/cluster' is an endpoint and '1' is the parameter; but if the URL is like '/cluster/A/1' and sometimes there is '/cluster/A, the code doesn't know if the 'A' part should be interpreted as a parameter or a part of the route. Flask and other frameworks may let users to define the URL format (such as '/cluster/{cluster_name}/{node_name}', while it's not impossible to implement, it takes much effort since AdminUI needs to coordinate a lot of parts due to its method of implementation.

So I think I'll decide to leave it be for now. You may try connecting parts or parameters using underscores("_") to satisfy immediate needs, maybe.

**Comment by jwag59** [comment]
I assume this also means that passing multiple parameters to a URL is also a NOGO?

**Comment by jwag59** [comment]
OK I have thought about it a bit more and in my case the work around is not very useful since I have a table with over 1000 entries and each have a View row action that should go to the same  URL with a parameter from the table entry which then does a DB lookup based on the parameter and shows more information. Clearly I can't make over 1000 @app.page decorators for each possible table entry that exists. In any case the number of entries in the table are not know ahead of time.

I'd like to suggest a possible workaround for this issues which I'd like you to consider.
And BTW I assume that for every @app.page decorator that adminui encounters it creates a route for that decorator. 
So would the following mechanism be possible.
If for example adminui sees a URL /cluster/node/1 it first checks to see if a route is defined as /cluster/node/1
If yes it calls this route, if not it then checks to see if a route /cluster/node is defined. If yes, it calls this route passing 1 as a parameter. If not then it checks to see if a route /cluster is defined and if yes then it runs this route passing both 'node' and 1 as parameters. And if not then a 404 error is raised.
This implementation is interesting in that it supports the passing of multiple parameters to a URL simply by adding more levels to the URL call.

Would that be possible to implement in adminui and which is not too complex?

**Comment by bigeyex** [comment]
If the multiple-parameter is the need, maybe a traditional "/node?cluster=1&node=13" like URL pattern would be better?
matching URL backward without a pattern definition is a little bit tricky I think.

**Comment by jwag59** [comment]
Certainly a traditional style URL is a reasonable way to go. 
I have to admit I don't use multiple parameters very often but occasionally I'd really like to.

**Comment by bigeyex** [comment]
multiple params is supported in 1.3.0.
https://python-adminui.readthedocs.io/en/latest/parameter.html
