### ISSUE TITLE
layout rendering

### ISSUE THREAD

**Issue by edwardsun** [bigeyex/python-adminui#4]
Hi,

I'm using Paragraph layout to render some texts dynamically, i.e., when selecting different rows of a table. I tried "object_paragraph.text = new contents", but the layout did not really reflect such change on the webpage. The same case also applies to other layouts like ChartCard. Could you please advise?

BTW, this is a great tool! Thanks for the project.

**Comment by bigeyex** [comment]
Implement via Page Actions in 0.3.0.
See 
https://python-adminui.readthedocs.io/en/latest/page_actions.html#update-page-content-in-page-actions
for details.
