### ISSUE TITLE
Request for Information: How can you serve up static files?

### ISSUE THREAD

**Issue by jwag59** [bigeyex/python-adminui#41]
I'd like to add images to the page via a RawHTML item but can't seem to specify any URL that can load the image.
I've tried a relative URL start with /static/logo.png and then I've also tried:
http://serverIP:8000/static/logo.png
As can be seen I've created a static subdirectory for my project  (and I'm using Flask as the base nor FastAPI) so how can I get the image to display?
I am trying to set:
1) An alternative logo 
2) An image to a Button (not an Adminui Button but a standard html button) 

Any help on how to server static files would be appreciated.

**Comment by bigeyex** [comment]
It needs a new feature to support additional static files. Added in 1.3.0
https://python-adminui.readthedocs.io/en/latest/static_files.html
