### ISSUE TITLE
Request to update the login page placeholders

### ISSUE THREAD

**Issue by jwag59** [bigeyex/python-adminui#49]
Can the placeholder text for the User name and Passowrd on the login page be updated please.
The current text is (also see screenshot below):
userName: admin or user
password: ant.design

Perhaps something more generic like the following could be used:
Your user name
Your password

The current login window looks like this:
![login_page_placeholders](https://user-images.githubusercontent.com/22910903/171594939-98685502-9261-46bb-aea3-af2f2a25865e.png)

**Comment by bigeyex** [comment]
fixed in 1.4.7
