### ISSUE TITLE
Table column filter icon is not displayed for a column with a Status badge defined

### ISSUE THREAD

**Issue by jwag59** [bigeyex/python-adminui#52]
When I add a filter option to a column that uses a status badge the filter icon is not displayed and therefore filtering cannot be used for that column.
As a test I applied the same filter to 2 different columns and the column without the status badge displays the filter icon but the one with the status badge does not.

This is my code defining the columns:
```
    table_columns = [
        {'title': 'Node', 'dataIndex': 'nodename', 'filters': op_filter},
        {'title': 'Status', 'dataIndex': 'status', 'filters': op_filter, 'status': 'statusBadge'},
        {'title': 'Nodegroup', 'dataIndex': 'ngname', 'filters': ng_filter, 'sorter': True},
        {'title': 'MAC', 'dataIndex': 'nodemac'},
        {'title': 'IP', 'dataIndex': 'nodeip'},
        {'title': 'Interface', 'dataIndex': 'netdev'},
    ]
```
My op_filter is defined as follows:
```
[{'text': 'Offline', 'value': 'Offline'}, {'text': 'Running', 'value': 'Running'}, {'text': 'Online', 'value': 'Online'}]
```
And when the table is displayed I get this:
![filter_not_shown](https://user-images.githubusercontent.com/22910903/171831856-996d4b7a-7d31-4816-b245-34d254fd71e6.png)

**Comment by bigeyex** [comment]
fixed in 1.4.8
