### ISSUE TITLE
CombinedAction(UpdateElements)

### ISSUE THREAD

**Issue by edwardsun** [bigeyex/python-adminui#6]
Hi,

Thank you so much for the package. It works like a charm so far!
I'm wondering if there can be a way to update multiple elements at the same time.
Currently I can do: return an UpdateElement in case of an on_click event.
I'd like to know how I can do CombinedAction([UpdateElement1, UpdateElement2]). (PS. I tried but obviously combinedaction did not work out.)

BTW I did think about updating a container that has multiple elements, but it seems difficult if multiple elements HAVE to be in different containers due to design purpose.

Thanks a lot for your help!

**Comment by bigeyex** [comment]
There is a bug in CombinedAction. Fixed in 0.3.1.
Now for convenience, you may also use a list [] instead of CombinedAction.
