### ISSUE TITLE
版本1.51  UpdateElement回调问题

### ISSUE THREAD

**Issue by chs5747** [bigeyex/python-adminui#63]
adminui版本
![image](https://user-images.githubusercontent.com/108145830/175607512-b4ce23e7-1772-4706-9450-939b8a6e2f40.png)
使用fastapi
![image](https://user-images.githubusercontent.com/108145830/175607680-786ad211-8855-4a6c-933c-435898705139.png)
页面配置
![image](https://user-images.githubusercontent.com/108145830/175608287-83590195-8352-4f8c-b62a-4b8aae6ef7a5.png)

结果
点击前
![image](https://user-images.githubusercontent.com/108145830/175607858-590e77a1-dc4d-429d-84df-36181d3837c9.png)
点击后
![image](https://user-images.githubusercontent.com/108145830/175607942-10cf7a63-0ff7-4a3a-99d9-7a06a986ba67.png)

**Comment by bigeyex** [comment]
UpdateElement的用法是，只更新一个东西的内容，而不是它本身。所以on_change_self应该是这种：
```
def on_change_self():
    return UpdateElement('a1', content=[
            DetailItem('Order No.', 1111),
            DetailItem('Status', "222"),
            DetailItem('Shipping No.', 3333),
            DetailItem('Sub Order', 444)
    ])
```

**Comment by chs5747** [comment]
收到，感谢。 
关闭issue。
