### ISSUE TITLE
为什么跳转不到登录

### ISSUE THREAD

**Issue by kirer** [bigeyex/python-adminui#66]
@app.page('/', 'Home', ['user'])
def home_page():
    return [
        Form(on_submit = on_submit, content = [
            TextField('Title', required_message="The title is required!"),
            TextArea('Description'),
            FormActions(content = [
                SubmitButton('Submit')
            ])
        ])
    ]
重定向到了http://127.0.0.1:5000/user/login?errorTitle=No%20Permission&errorMsg=Please%20login%20first%20or%20contact%20your%20administrator
404 Not Found

**Comment by bigeyex** [comment]
resolved by another PR
