### ISSUE TITLE
rich text paragraph

### ISSUE THREAD

**Issue by edwardsun** [bigeyex/python-adminui#7]
Hi,
I'm using to tool to display a paragraph, and notice that "newline"s are not properly shown. There are '\r\n's in texts, but the separators are unfortunately ignored. I guess I should try to replace '\r\n' with some strings to get them working. Any suggestions?

Another broader question. If I want to show color/different-font text, what should I do? Maybe inserting some XML/HTML formatted string?
Thanks!

**Comment by bigeyex** [comment]
Hmm, will find time to address this nl2br issue.
Color controls of elements are on the roadmap. But I'm also thinking about adding a HTML element / allowing users to define their own element.

**Comment by bigeyex** [comment]
Now newlines work in Paragraph in 0.3.1.
And you may add color attribute in Paragraphs, like:
`Paragraph("I'm a paragraph", color="red")`

**Comment by edwardsun** [comment]
Thank you so much for the help!
I actually need to change different keywords in a paragraph with different colors and fonts. Initially my guessed solution was to replace keywords with some notation. eg.

.... key words ...  => ... key words <color = red, fontsize = 12/> ...

I guess this would be a lot more flexible for users, but not sure how difficult to really implement.

Thanks.

**Comment by bigeyex** [comment]
While it's not the best solution, in the new 0.3.2 you may use something like
`RawHTML('a raw <font color="red">HTML</font>')`
