### ISSUE TITLE
deployment

### ISSUE THREAD

**Issue by edwardsun** [bigeyex/python-adminui#8]
Hi,

How can I deploy the tool into production? 
i.e. access via web from another computer, adding SSL certificates, etc.

Great tool, BTW.

Thanks.

**Comment by edwardsun** [comment]
Perhaps the base class or an adapter can inherit a flask app class, so that people can use tornado to do things like:
from tornado.wsgi import WSGIContainer
from tornado.httpserver import HTTPServer

http_server = HTTPServer(WSGIContainer(app))
http_server.ssl_options = {
            "certfile": cert,
            "keyfile": keyfile
       }

**Comment by edwardsun** [comment]
currently i encountered this error if I was using tornado:
        http_server.listen(port,address='0.0.0.0')
        IOLoop.instance().start()

![image](https://user-images.githubusercontent.com/359830/73327000-3d1f3c80-4222-11ea-82ef-ff8113c440fd.png)

**Comment by bigeyex** [comment]
try app.app in 
`http_server = HTTPServer(WSGIContainer(app))`

This is because app is an instance of AdminApp, which is not what Tornado is looking for;
app.app refers to the underlying Flask app.

**Comment by edwardsun** [comment]
I did:
app = AdminApp()
http_server = HTTPServer(WSGIContainer(app.app))
http_server.listen(port,address='0.0.0.0')
IOLoop.instance().start()

And got: 
![image](https://user-images.githubusercontent.com/359830/73360858-c873ee80-4271-11ea-8226-5634446b57c5.png)

It seems I might have missed some steps in which app.run() invokes.
Any thoughts?

**Comment by bigeyex** [comment]
After some googling, I found that tornado is not an officially supported Flask deployment method. So it's unknown what feature is supported and what is not. Maybe one of [the official methods](https://flask.palletsprojects.com/en/1.1.x/deploying/) is more preferable?

In my experiment, tornado responds to both static or dynamic content with 404. So maybe there's some problem between tornado and Flask application.

**Comment by edwardsun** [comment]
I tried gevent.
app = AdminApp()
http_server = WSGIServer(('0.0.0.0', 5000), app)
http_server.serve_forever()
![image](https://user-images.githubusercontent.com/359830/73370969-0a596080-4283-11ea-8fd1-40e433a9662b.png)

Then I tried:
http_server = WSGIServer(('0.0.0.0', 5000), app.app)
![image](https://user-images.githubusercontent.com/359830/73371171-47bdee00-4283-11ea-8fc6-be068139972c.png)
But app seems to be configured correctly in my code.
![image](https://user-images.githubusercontent.com/359830/73371233-63c18f80-4283-11ea-9230-db30a14a6a7c.png)

**Comment by edwardsun** [comment]
I was able to modify the app.py code to split the orignal app.run() method into two steps, the first being self.app (the flask object) preparation, and the second simply self.app.run(). I just needed to call the first step. The quick "solution" solved my problem. Might be worthwhile to adopt. Just FYI and thanks for the nice tool.

**Comment by edwardsun** [comment]
Currently my solution is to inherit a subclass from AdminApp, and write a function that copies the same behavior as the adminapp.run()'s all steps except the last step. Is there a plan to add such method in AdminApp class?

**Comment by bigeyex** [comment]
addressed in 0.3.5. 
now assume app is an AdminApp, you can use 
`app.prepare()` to do the preparation and get a Flask App instance as the return.
