### ISSUE TITLE
page with params

### ISSUE THREAD

**Issue by edwardsun** [bigeyex/python-adminui#9]
Hi,
I'm trying to add parameters to a webpage. 
With reference to the example in the project, i.e., 
@app.page('/article', 'Article')
def form_page(param):
    return [ ... the content of the page ... ]
I'd like to set param to a string representing a date range. eg. param = '20100201-20200101'
However, the above string could not be caught.
After poking around a bit, it turned out the param can only be a literal string without special characters. 

I'd like to suggest the param to be more flexible.
Or more generically, it would be great to be use REST api in the param to specify parameters.

**Comment by bigeyex** [comment]
The parameter will appear on the URL(browser address bar), so it must be a string literal. It is also common in many websites to use a date-string in the URL(and parse it on backend).

Supporting REST API is not the purpose of this library(after all it's a UI framework), however, using Flask app object exposed as `app.app`, you may add as many endpoints as you wish, as long as you don't claim the url patterns used by adminui.

**Comment by edwardsun** [comment]
Thanks
